### ISSUE TITLE
magnifying glass doesn't work for images in placeholders

### ISSUE THREAD

**Issue by damithc** [PowerPointLabs/repo#625]
If you select an image that is also a placeholder and apply magnifying glass it gives a 'crop to shape' error message followed by an 'undefined error' message

**Comment by nevet** [comment]
It works fine on both my computer and labs' computer. I try to reproduce using the following procedure:

1. Select the content place holder;
2. Choose "Insert Picture", and choose a picture to fill up the place holder;
3. Place a shape above the place holder;
4. Select "Magnify Glass"/ "Recolor Remainder".

**Comment by damithc** [comment]
I cannot reproduce either. Can close
