### ISSUE TITLE
"Please check you network connection and try again" when install

### ISSUE THREAD

**Issue by kai33** [PowerPointLabs/repo#690]
1. special char is detected in the install path, thus offline installer cannot handle and try to download the web installer.
2. some exception is thrown when download & extract the package.

**Comment by kai33** [comment]
this issue affects Euro users, with username not in entirely English

**Comment by kai33** [comment]
Sol: make offline installer install from system disk (eg C:\pptlabs\) if the user folder path has special char. and when update, also update from it if user folder path has special char.

**Comment by kai33** [comment]
Resolved by commit cdae05f7db2e2a2d37f287f86d7a541e74e6dc7d, 5e3000dafa979754efe1b2cf8f83c393153a78f2, 0ee9b734bdff6ec4fdf459b92ca9a13ecdce3f17

manually tested done.
pushed version 1.11.0.0 with new installer and updater.

hopefully, no need the web installer any more

**Comment by damithc** [comment]
Thanks Kai.
